name: Incite Local Mobile
favicon: null
layout_spectrum: 0.2047890448011458
typography_spectrum: 0.41521669132635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2369113101158291
  lightness: 0.5647351716179401
  saturation: 0.10711331386119127
  rhythmicContrast: 0.19433940947055817
purpose: []
